DROP DATABASE IF EXISTS maze_db;
CREATE DATABASE maze_db;

USE maze_db;

CREATE TABLE users (
    id INTEGER(100) NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE user_times (
    id INTEGER(100) NOT NULL AUTO_INCREMENT,
    time DECIMAL(10) NOT NULL,
    PRIMARY KEY (id)
);